# Service alias for memcached
# The application expects "iqgeo-memcached" but Helm creates "iqgeo-iqgeo-memcached"
# This service aliases the memcached service to match application expectations
apiVersion: v1
kind: Service
metadata:
  name: iqgeo-memcached
  namespace: iqgeo
spec:
  type: ClusterIP
  ports:
    - port: 11211
      targetPort: 11211
      protocol: TCP
      name: memcache
  selector:
    app.kubernetes.io/name: memcached
    app.kubernetes.io/instance: iqgeo

