# EFS Storage Class for IQGeo
# Note: PVC will be created by Helm chart, not manually
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: efs-sc
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  fileSystemId: fs-0f64028caf280776d
  directoryPerms: "700"
  gidRangeStart: "1000"
  gidRangeEnd: "2000"
  basePath: "/iqgeo"
reclaimPolicy: Retain
volumeBindingMode: Immediate

